"""add ML training columns

Revision ID: 1c5262348f44
Revises: 7b797c4ffef8
Create Date: 2026-04-30 00:52:48.900960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5262348f44'
down_revision: Union[str, Sequence[str], None] = '7b797c4ffef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('coil_voltage', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('vibration', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('failure_mode', sa.String(), nullable=True))
    op.add_column('telemetry', sa.Column('time_to_failure_s', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('will_fail_10min', sa.Boolean(), nullable=True))
    op.add_column('telemetry', sa.Column('ai_anomaly_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'ai_anomaly_score')
    op.drop_column('telemetry', 'will_fail_10min')
    op.drop_column('telemetry', 'time_to_failure_s')
    op.drop_column('telemetry', 'failure_mode')
    op.drop_column('telemetry', 'vibration')
    op.drop_column('telemetry', 'coil_voltage')
    # ### end Alembic commands ###
