"""initial schema

Revision ID: 7b797c4ffef8
Revises: 
Create Date: 2026-04-30 00:47:08.692093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b797c4ffef8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('session_start_time', sa.DateTime(), nullable=True),
    sa.Column('last_export_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_runs_id'), 'sim_runs', ['id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sim_run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_sim', sa.DateTime(), nullable=False),
    sa.Column('induction_power', sa.Float(), nullable=False),
    sa.Column('quench_water_temp', sa.Float(), nullable=False),
    sa.Column('quench_water_flow', sa.Float(), nullable=False),
    sa.Column('quench_pressure', sa.Float(), nullable=False),
    sa.Column('coil_scan_speed', sa.Float(), nullable=False),
    sa.Column('part_temp', sa.Float(), nullable=True),
    sa.Column('part_id', sa.String(), nullable=True),
    sa.Column('shift_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('coil_life_counter', sa.Integer(), nullable=True),
    sa.Column('ok_count', sa.Integer(), nullable=True),
    sa.Column('ng_count', sa.Integer(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('downtime_reason', sa.String(), nullable=True),
    sa.Column('ng_reason', sa.String(), nullable=True),
    sa.Column('repair_time', sa.Float(), nullable=True),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('ai_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sim_run_id'], ['sim_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_timestamp', 'telemetry', ['timestamp_sim'], unique=False)
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_index('idx_telemetry_timestamp', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_sim_runs_id'), table_name='sim_runs')
    op.drop_table('sim_runs')
    # ### end Alembic commands ###
